### ISSUE TITLE
Can you update the readme to include Windows users with private repo dependencies?

### ISSUE THREAD

**Issue by commadore** [composer/docker#155]
`$ eval $(ssh-agent); \
  docker run --rm --interactive --tty \
  --volume $PWD:/app \
  --volume $SSH_AUTH_SOCK:/ssh-auth.sock \
  --env SSH_AUTH_SOCK=/ssh-auth.sock \
  composer install`

Is fine for Linux users (mac maybe too?), but can't work for Windows users.
I currently use git bash in Windows 10, and I had to make a bespoke image which I used a volume to map my .ssh folder into /tmp/.ssh, then runs this under the hood before running the composer command:

`cp -R /tmp/.ssh /root/.ssh`
`chmod 700 /root/.ssh`
`chmod 644 /root/.ssh/id_rsa.pub`
`chmod 600 /root/.ssh/id_rsa`

It doesn't work for everyone though and I'm really hoping you know more than I do on how to solve this issue.

**Comment by alcohol** [comment]
I honestly do not know much about running Docker on Windows. I only develop on Linux (and Mac in the past). The work-around for Mac is somewhat well known and documented, hence why I included it. A quick Google search for Windows yields me https://pscheit.medium.com/use-an-ssh-agent-in-wsl-with-your-ssh-setup-in-windows-10-41756755993e as one of the first results. But if offers multiple solutions and I am not able to test any of them, so I feel uncomfortable adding those to our "official" documentation since I cannot support nor validate them. If you (and other Windows) users can validate a solution that works, I will gladly add it though.

**Comment by phpguru** [comment]
Use Docker for Windows under WSL2.
