### ISSUE TITLE
v2.0.9 introduces PHP 8 from PHP 7.4

### ISSUE THREAD

**Issue by do-io** [composer/docker#161]

**Comment by do-io** [comment]
v2.0.8 pulled PHP 7.4

v2.0.9 pulled PHP 8

**Comment by wahyudibo** [comment]
Agree, i got surprised when our cicd failed to build yesterday and errors said that the compatibility of our packages are broken due to the composer docker image upgrade to php:8. Can i suggest to add more tag for clarity ? like `composer:2-php7` and `composer:2-php8` ?

btw thanks @do-io for your comment, will stick to `2.0.8` tag for now

**Comment by chivincent-rosetta** [comment]
I made the PR for upgrading to PHP 8 because I worked on this version for a while. I'm sorry that it broke your packages and CI.
I think making a new docker version tag such as `composer:1-php8` and `composer:2-php8` could be helpful. It can be identified between PHP7 and PHP8.

**Comment by alcohol** [comment]
While inconvenient, it is clearly documented that you should not rely on the php version of our image.

https://github.com/docker-library/docs/tree/master/composer#php-version--extensions

**Comment by lekkerduidelijk** [comment]
@alcohol Thanks for the reference. Will stick to my own forks for CI/CD (which is probably more resilient in the long run anyway 😄 ).
